// Mocks generated by Mockito 5.4.6 from annotations
// in fashion_shop/test/features/auth/send_otp_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:fashion_shop/core/errors/failures.dart' as _i5;
import 'package:fashion_shop/features/auth/domain/entities/auth_entity.dart'
    as _i7;
import 'package:fashion_shop/features/auth/domain/entities/otp_entity.dart'
    as _i6;
import 'package:fashion_shop/features/auth/domain/repositories/auth_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i3.AuthRepository {
  MockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.OtpEntity>> sendOtp({
    required String? phoneNumber,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#sendOtp, [], {#phoneNumber: phoneNumber}),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i6.OtpEntity>>.value(
                  _FakeEither_0<_i5.Failure, _i6.OtpEntity>(
                    this,
                    Invocation.method(#sendOtp, [], {
                      #phoneNumber: phoneNumber,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.OtpEntity>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i7.AuthEntity>> verifyOtp({
    required String? phoneNumber,
    required String? otp,
    required String? verificationId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#verifyOtp, [], {
              #phoneNumber: phoneNumber,
              #otp: otp,
              #verificationId: verificationId,
            }),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i7.AuthEntity>>.value(
                  _FakeEither_0<_i5.Failure, _i7.AuthEntity>(
                    this,
                    Invocation.method(#verifyOtp, [], {
                      #phoneNumber: phoneNumber,
                      #otp: otp,
                      #verificationId: verificationId,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i7.AuthEntity>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
              _FakeEither_0<_i5.Failure, void>(
                this,
                Invocation.method(#logout, []),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, bool>> isLoggedIn() =>
      (super.noSuchMethod(
            Invocation.method(#isLoggedIn, []),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, bool>>.value(
              _FakeEither_0<_i5.Failure, bool>(
                this,
                Invocation.method(#isLoggedIn, []),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, bool>>);
}
